source 'https://rubygems.org'

ruby "2.5.0"

gem "feedjira", "~> 3.1"

gem "httparty", "~> 0.17.3"

gem "aws-record", "~> 2.4"

gem "aws-sdk-s3", "~> 1.60"

gem "aws-sdk-dynamodb", "~> 1.41"

gem "aws-sdk-eventbridge", "~> 1.3"

gem "upmark", "~> 1.0"

gem "nokogiri", "~> 1.10"
