source 'https://rubygems.org'

gem "feedjira", "~> 3.1"

gem "httparty", "~> 0.17.3"

gem "aws-record", "~> 2.4"

gem "aws-sdk-s3", "~> 1"

gem "aws-sdk-dynamodb", "~> 1"

gem "aws-sdk-eventbridge", "~> 1"

gem "kramdown", "~> 2.3"

gem "nokogiri", "~> 1.10"
